---
title: "Lab 1"
author: "Popov Ivan"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

# Task 1

```{r}
setwd("~/develop/studyR")
source("source/lab1/task1.r")
df <- read.csv("data/lab1_e1.csv",sep=',')

# helper function to process each value in df
fix_entry <- function(entry) {
  tryCatch(
    { as.numeric(gsub(" ", "", entry)) },
    error = function(cond) entry,
    warning = function(cond) entry,
    finally = {}
  ) 
}

fix_data <- function(df) {
  sapply(df, function(obs) lapply(obs, fix_entry))
}
fix_data(df)
```

# Task 2

```{r}
setwd("~/develop/studyR")
source("source/lab1/task2.r")
load("data/lab1_e2.Rdata") 
merge <- function(data) {
  list_tables <- lapply(data, function(week_table) Reduce(c, list(week_table)))
  do.call(rbind, list_tables)
}

## right solution, readable and w/t tons of unnecessary code 
# library(dplyr)

# get_id <- function(all_data) {
#     merged_table <- merge(all_data)  
#     merged_table %>% group_by(id)  %>%
#     summarise(mean_temp = mean(temp),
#               count = n(),
#               .groups = 'drop') %>% filter(count == 7) %>% select(id, mean_temp)
# }
# get_id(all_data)



get_id <- function(all_data) {
  
  merged_table <- merge(all_data)
  
  tmp<-data.frame(id=integer(), total_temp=double(), count=integer())
  for (row in 1:nrow(merged_table)){
    entry <- merged_table[row,]
    if (nrow(tmp[which(tmp$id==entry$id),]) == 0){
      tmp[nrow(tmp)+1,] <- c(entry$id, entry$temp, 1)
    } else {
      prev_val <- tmp[which(tmp$id==entry$id),]
      tmp[which(tmp$id==entry$id),] <-c(prev_val$id, prev_val$total_temp + entry$temp, prev_val$count + 1) 
    }
  }
  
  full_week <- tmp[tmp$count==7,]
  data.frame(id = full_week$id, mean_temp = full_week$total_temp / 7)
}
get_id(all_data)
```
